### ISSUE TITLE
Uploaded files were removed automatically

### ISSUE THREAD

**Issue by Thalla** [biocypher/ChatGSE#7]
I left ChatGSE alone for some minutes (at the point of having to describe my data in more detail) and when I came back and wanted to go on with the chat, the page reloaded and removed my uploaded files. It's not indicated anywhere that this can happen, is it? And the timeframe is very short.

**Comment by slobentanzer** [comment]
That's interesting; I never waited in between. Maybe this is caused by the streamlit cloud hosting? Wouldn't make a lot of sense, but if so, we could maybe fix it by hosting the app ourselves. I'll do some tests.

You're right that we should warn if this happens consistently.
